### ISSUE TITLE
very_minimal.asm setting auto-increment to 0 not 2?

### ISSUE THREAD

**Issue by NicholasBHubbard** [namalgo/genesis#1]
Here is [line 163](https://github.com/namalgo/genesis/blob/main/src/very_minimal/very_minimal.asm#LL163C8-L163C8) of `very_minimal.asm`:
```
move.w  #$8F00,vdp_control     ; Set VDP autoincrement to 2 words/write
```
Isn't this setting the auto-increment to 0 as the lower byte getting written to vdp_control is 0? 

To set the auto increment to two words/write I would instead expect this:
```
move.w  #$8F02,vdp_control
```
Let me know if I am missing something.

**Comment by namalgo** [comment]
You are absolutely right, that's a typo. I will correct.
